title = "raphael0io"
theme = "solar-theme-hugo" # bethebestyou-theme-hugo solar-theme-hugo
paginate = 5
pygmentsStyle = "solarized-dark256" # solarized-light, -dark or -dark256
#baseurl = "http://raphael0.io"
baseurl = "http://raphael0.io.website-eu-central-1.linodeobjects.com/"
languageCode = "de"

[params]
  scheme = "dark" # light, dark or gray
  description = "Place to share Information and explore new Tech"
  
[menu]
  [[menu.main]]
    name = "RSS-Feed"
    url = "/index.xml"
    weight = "-100"
  [[menu.main]]
    name = "#bethebestyou"
    url = "http://bethebestyou.de"
    weight = "0"
  [[menu.other]]
    name = "Code"
    url = "https://github.com/raphael0io"
  [[menu.other]]
    name = "Faceit"
    url = "https://www.faceit.com/de/players/raphael0io"
  [[menu.other]]
    name = "Instagram"
    url = "https://www.instagram.com/raphael0io/"
  [[menu.other]]
    name = "Medium"
    url = "https://medium.com/@raphael0io"
  [[menu.other]]
    name = "Reddit"
    url = "https://old.reddit.com/user/raphael_0/"
  [[menu.other]]
    name = ""
    url = ""


