title = "thoughts"
# bethebestyou-theme-hugo solar-theme-hugo
theme = "solar-theme-hugo"
paginate = 5
pygmentsStyle = "solarized-dark256" # solarized-light, -dark or -dark256

[params]
  scheme = "dark" # light, dark or gray
  description = "Place to share Information and explore new Tech"
  theme = "bethebestyou-hugo"
# paginate = 5
# pygmentsStyle = "solarized-dark256" # solarized-light, -dark or -dark256

[params]
  theme = "bethebestyou-hugo"
# paginate = 5
# pygmentsStyle = "solarized-dark256" # solarized-light, -dark or -dark256

[params]
#  scheme = "dark" # light, dark or gray
  description = "Place to share Inforamtion and explore new Tech"

[menu]
  [[menu.main]]
    name = "Feed"
    url = "/"
    weight = "-100"
  [[menu.main]]
    name = "#bethebestyou"
    url = "http://bethebestyou.de"
    weight = "0"
  [[menu.other]]
    name = "Code"
    url = "https://github.com/raphael092"
  [[menu.other]]
    name = "Faceit"
    url = "https://www.faceit.com/de/players/pawN_0"
  [[menu.other]]
    name = "Instagram"
    url = "https://www.instagram.com/raphael0/"
  [[menu.other]]
    name = "Medium"
    url = "https://medium.com/@raphael0"
  [[menu.other]]
    name = "Nextcloud"
    url = "https://nextcloud.raphael0.io"
  [[menu.other]]
    name = "Reddit"
    url = "https://old.reddit.com/user/raphael_0/"
  [[menu.other]]
    name = ""
    url = ""
languageCode = "de"

